name: Test Eslint

on: 
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-verson: 20